<a href="https://colab.research.google.com/github/AyaTareekAhmmeed/numpy-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [3]:
array1 = np.array([10,20,30,40]) #rank1
print(array1)

[10 20 30 40]


In [4]:
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(4,)


In [5]:
array1[1]=50
print(array1[1])
print(array1)

50
[10 50 30 40]


In [6]:
array2 = np.array([[10,20,30,40],[50,60,70,80]]) #rank2
print(array2)
print(type(array2))
print(array2.shape)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
(2, 4)


In [7]:
#slicing 1D
print(array1[0:3])

[10 50 30]


In [8]:
#slicing 2D
print(array2[0:,0:2])

[[10 20]
 [50 60]]


In [9]:
#to access spasific element 70
print(array2[1:2,2:3])

[[70]]


In [11]:
#zero array
zero_array = np.zeros((4,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#one array
one_array = np.ones((3,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#constant array
constant_type_array = np.full((2,2),5)
print(constant_type_array)

[[5 5]
 [5 5]]


In [16]:
#identity array
ident = np.eye(5)
print(ident)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
#random array
#can not force element in random array to be integer
random_array = np.random.random((3,3))
print(random_array)

[[0.56174846 0.71393337 0.42664204]
 [0.43116148 0.20399406 0.77923428]
 [0.51703959 0.34295287 0.72180114]]


In [18]:
#arithmetic operation 
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,20,30],[40,50,60]])
print(np.add(x,y))
print(np.subtract(y,x))
print(np.multiply(x,y))
print(np.divide(y,x))
print(np.sqrt(y))

[[11 22 33]
 [44 55 66]]
[[ 9 18 27]
 [36 45 54]]
[[ 10  40  90]
 [160 250 360]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [22]:
#dot product of diif dimension ".dot"
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])

v = np.array([8,9])
w = np.array([5,7])
print(m.dot(n))
print(v.dot(w))
print(m.dot(v))


[[19 22]
 [43 50]]
103
[26 60]


In [23]:
#transpose ".T"
print('original matrix:',m)
print('transpose matrix:',m.T)

original matrix: [[1 2]
 [3 4]]
transpose matrix: [[1 3]
 [2 4]]


In [24]:
#utilizing broadcasting 
f = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
e = np.array([1,0,1])
sum_of_vectors = f+e
print(sum_of_vectors)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
